;; -*- lexical-binding: t -*-

(require 'retro (expand-file-name "./../retro.el"))

(defun walk-demo ()
  "Move an animated sprite left and right."
  (let ((width 320)
        (height 240))
    (retro-game-create :name "walk"
                       :resolution (cons width height)
                       :background-color (ht-get retro-palette-colors->index "#ffffff")
                       :bind `((("<left>" "h") . ,(lambda (game-state _)
                                                    (let* ((sprite (nth 1 game-state))
                                                           (sx (retro-sprite-x sprite))
                                                           (sw (retro-sprite-width sprite)))
                                                      (if (< sx (- sw))
                                                          (setf (retro-sprite-x sprite) (1- width))
                                                        (setf (retro-sprite-x sprite) (- sx 2))))
                                                    (retro--next-frame-sprite (nth 1 game-state))
                                                    (when (nth 2 game-state)
                                                      (retro--flip-h-sprite (nth 1 game-state))
                                                      (setf (nth 2 game-state) nil))
                                                    ))
                               (("<right>" "l") . ,(lambda (game-state _)
                                                     (let* ((sprite (nth 1 game-state))
                                                            (sx (retro-sprite-x sprite))
                                                            (sw (retro-sprite-width sprite)))
                                                       (if (> sx (1- width))
                                                           (setf (retro-sprite-x sprite) (- sw))
                                                         (setf (retro-sprite-x sprite) (+ sx 2))))
                                                     (retro--next-frame-sprite (nth 1 game-state))
                                                     (when (not (nth 2 game-state))
                                                       (retro--flip-h-sprite (nth 1 game-state))
                                                       (setf (nth 2 game-state) t))
                                                     ))
                               ("q" . retro--handle-quit))
                       :init (lambda () (list 0 (retro--load-sprite "./asset/walk-demo.sprite" 10 160) t))
                       :update (lambda (_elapsed game-state _canvas)
                                 (cl-incf (car game-state)))
                       :render (lambda (_elapsed game-state canvas)
                                 (retro--plot-sprite (nth 1 game-state) canvas)))))

(defun walk-demo-start ()
  (interactive)
  (retro--game-loop (walk-demo)))
